#                                           numpy 练习题

### numpy 的array操作

#### 1.导入numpy库

In [37]:
import numpy as np

#### 2.建立一个一维数组 a 初始化为[4,5,6], (1)输出a 的类型（type）(2)输出a的各维度的大小（shape）(3)输出 a的第一个元素（值为4）

In [38]:
a = np.array([4, 5, 6])
print(f"The type of a:{type(a)}")
print(f"The shape of a:{a.shape}")
print(f"The first element in a is:{a[0]}")

The type of a:<class 'numpy.ndarray'>
The shape of a:(3,)
The first element in a is:4


#### 3.建立一个二维数组 b,初始化为 [ [4, 5, 6],[1, 2, 3]] (1)输出各维度的大小（shape）(2)输出 b(0,0)，b(0,1),b(1,1) 这三个元素（对应值分别为4,5,2）

In [39]:
b = np.array([[4, 5, 6], [1, 2, 3]])
print(f"the shape of b:{b.shape}")
print(f"b(0, 0):{b[0][0]}, b(0,1):{b[0][1]}, b(0,2):{b[0][2]}")


the shape of b:(2, 3)
b(0, 0):4, b(0,1):5, b(0,2):6


#### 4.  (1)建立一个全0矩阵 a, 大小为 3x3; 类型为整型（提示: dtype = int）(2)建立一个全1矩阵b,大小为4x5;  (3)建立一个单位矩阵c ,大小为4x4; (4)生成一个随机数矩阵d,大小为 3x2.

In [40]:
# (1) 建立一个全0矩阵 a, 大小为 3x3; 类型为整型
a = np.zeros((3, 3), dtype=int)
print(f"全0矩阵a:\n{a}")

# (2) 建立一个全1矩阵 b, 大小为 4x5
b = np.ones((4, 5))
print(f"全1矩阵b:\n{b}")

# (3) 建立一个单位矩阵 c, 大小为 4x4
c = np.eye(4)
print(f"单位矩阵c:\n{c}")

# (4) 生成一个随机数矩阵 d, 大小为 3x2
d = np.random.rand(3, 2)
print(f"随机数矩阵d:\n{d}")


全0矩阵a:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
全1矩阵b:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
单位矩阵c:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
随机数矩阵d:
[[0.37853404 0.5731789 ]
 [0.2448741  0.90952395]
 [0.69596944 0.09656428]]


#### 5. 建立一个数组 a,(值为[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] ) ,(1)打印a; (2)输出  下标为(2,3),(0,0) 这两个数组元素的值

In [41]:
# (1) 建立一个数组 a, 值为 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# (2) 打印数组 a
print(f"数组a:\n{a}")

# (3) 输出下标为 (2, 3) 和 (0, 0) 的两个数组元素的值
element_2_3 = a[2, 3]  # 下标 (2, 3) 的元素
element_0_0 = a[0, 0]  # 下标 (0, 0) 的元素

print(f"下标为(2, 3)的元素值: {element_2_3}")
print(f"下标为(0, 0)的元素值: {element_0_0}")

数组a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
下标为(2, 3)的元素值: 12
下标为(0, 0)的元素值: 1


#### 6.把上一题的 a数组的 0到1行 2到3列，放到b里面去，（此处不需要从新建立a,直接调用即可）(1),输出b;(2) 输出b 的（0,0）这个元素的值

In [42]:

# 把 a 数组的 0 到 1 行、2 到 3 列放到 b 里面去
b = a[0:2, 2:4]  # 提取 a 的第 0 和第 1 行，第 2 和第 3 列

# (1) 输出 b
print(f"数组b:\n{b}")

# (2) 输出 b 的 (0, 0) 元素值
element_0_0_b = b[0, 0]
print(f"数组b 的 (0, 0) 元素值: {element_0_0_b}")

数组b:
[[3 4]
 [7 8]]
数组b 的 (0, 0) 元素值: 3


 #### 7. 把第5题中数组a的最后两行所有元素放到 c中，（提示： a[1:2, :]）(1)输出 c ; (2) 输出 c 中第一行的最后一个元素（提示，使用 -1                 表示最后一个元素）

In [43]:
# 把第5题中数组 a 的最后两行所有元素放到 c 中
c = a[1:3, :]  # 提取第 1 和第 2 行的所有列

# (1) 输出 c
print(f"数组c:\n{c}")

# (2) 输出 c 中第一行的最后一个元素
element_last_of_first_row = c[0, -1]  # 第一行的最后一个元素
print(f"数组c 中第一行的最后一个元素值: {element_last_of_first_row}")

数组c:
[[ 5  6  7  8]
 [ 9 10 11 12]]
数组c 中第一行的最后一个元素值: 8


#### 8.建立数组a,初始化a为[[1, 2], [3, 4], [5, 6]]，输出 （0,0）（1,1）（2,0）这三个元素（提示： 使用 print(a[[0, 1, 2], [0, 1, 0]]) ）

In [44]:
# (1) 建立数组 a，初始化为 [[1, 2], [3, 4], [5, 6]]
a = np.array([[1, 2], [3, 4], [5, 6]])

# (2) 输出（0,0）、（1,1）、（2,0）这三个元素
selected_elements = a[[0, 1, 2], [0, 1, 0]]  # 使用高级索引
print(f"选中的元素值: {selected_elements}")  # 输出 [1, 4, 5]

选中的元素值: [1 4 5]


#### 9.建立矩阵a ,初始化为[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]，输出(0,0),(1,2),(2,0),(3,1) (提示使用 b = np.array([0, 2, 0, 1])                     print(a[np.arange(4), b]))

In [45]:
# (1) 建立矩阵 a，初始化为 [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# (2) 定义一个数组 b，表示要提取的列索引
b = np.array([0, 2, 0, 1])

# (3) 输出 (0,0), (1,2), (2,0), (3,1) 这四个元素
selected_elements = a[np.arange(4), b]
print(f"选中的元素值: {selected_elements}")  # 输出 [1, 6, 7, 11]

选中的元素值: [ 1  6  7 11]


#### 10.对9 中输出的那四个元素，每个都加上10，然后重新输出矩阵a.(提示： a[np.arange(4), b] += 10 ）

In [46]:
# (1) 建立矩阵 a，初始化为 [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

# (2) 定义一个数组 b，表示要提取的列索引
b = np.array([0, 2, 0, 1])

# (3) 对第9题中输出的那四个元素每个都加上 10
a[np.arange(4), b] += 10

# (4) 输出修改后的矩阵 a
print(f"修改后的矩阵a:\n{a}")

修改后的矩阵a:
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### array 的数学运算

#### 11.  执行 x = np.array([1, 2])，然后输出 x 的数据类型

In [47]:
# (1) 执行 x = np.array([1, 2])
x = np.array([1, 2])

# (2) 输出 x 的数据类型
print(f"x 的数据类型: {x.dtype}")

x 的数据类型: int32


#### 12.执行 x = np.array([1.0, 2.0]) ，然后输出 x 的数据类类型

In [48]:
# (1) 执行 x = np.array([1.0, 2.0])
x = np.array([1.0, 2.0])

# (2) 输出 x 的数据类型
print(f"x 的数据类型: {x.dtype}")

x 的数据类型: float64


#### 13.执行 x = np.array([[1, 2], [3, 4]], dtype=np.float64) ，y = np.array([[5, 6], [7, 8]], dtype=np.float64)，然后输出 x+y ,和 np.add(x,y)

In [49]:
# (1) 执行 x = np.array([[1, 2], [3, 4]], dtype=np.float64)
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 执行 y = np.array([[5, 6], [7, 8]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# (3) 输出 x + y 和 np.add(x, y)
print("x + y 的结果:")
print(x + y)

print("np.add(x, y) 的结果:")
print(np.add(x, y))

x + y 的结果:
[[ 6.  8.]
 [10. 12.]]
np.add(x, y) 的结果:
[[ 6.  8.]
 [10. 12.]]


#### 14. 利用 13题目中的x,y 输出 x-y 和 np.subtract(x,y)

In [50]:
#  输出 x - y 和 np.subtract(x, y)
print("x - y 的结果:")
print(x - y)

print("np.subtract(x, y) 的结果:")
print(np.subtract(x, y))

x - y 的结果:
[[-4. -4.]
 [-4. -4.]]
np.subtract(x, y) 的结果:
[[-4. -4.]
 [-4. -4.]]


#### 15. 利用13题目中的x，y 输出 x*y ,和 np.multiply(x, y) 还有  np.dot(x,y),比较差异。然后自己换一个不是方阵的试试。

In [51]:
#  输出 x * y 和 np.multiply(x, y)
print("x * y 的结果:")
print(x * y)

print("np.multiply(x, y) 的结果:")
print(np.multiply(x, y))

# 输出 np.dot(x, y)
print("np.dot(x, y) 的结果:")
print(np.dot(x, y))

# 换一个不是方阵的例子
x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)  # 2x3 矩阵
y = np.array([[7, 8], [9, 10], [11, 12]], dtype=np.float64)  # 3x2 矩阵

# 输出 np.dot(x, y)
print("np.dot(x, y) 的结果:")
print(np.dot(x, y))

x * y 的结果:
[[ 5. 12.]
 [21. 32.]]
np.multiply(x, y) 的结果:
[[ 5. 12.]
 [21. 32.]]
np.dot(x, y) 的结果:
[[19. 22.]
 [43. 50.]]
np.dot(x, y) 的结果:
[[ 58.  64.]
 [139. 154.]]


#### 16. 利用13题目中的x,y,输出 x / y .(提示 ： 使用函数 np.divide())

In [52]:
# (1) 使用 13 题目中的 x 和 y
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# (2) 输出 x / y 和 np.divide(x, y)
print("x / y 的结果:")
print(x / y)

print("np.divide(x, y) 的结果:")
print(np.divide(x, y))

x / y 的结果:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
np.divide(x, y) 的结果:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### 17. 利用13题目中的x,输出 x的 开方。(提示： 使用函数 np.sqrt() )

In [53]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 输出 x 的开方结果
print("x 的开方结果:")
print(np.sqrt(x))

x 的开方结果:
[[1.         1.41421356]
 [1.73205081 2.        ]]


#### 18.利用13题目中的x,y ,执行 print(x.dot(y)) 和 print(np.dot(x,y))

In [54]:
# (1) 使用 13 题目中的 x 和 y
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# (2) 执行 x.dot(y) 和 np.dot(x, y)
print("x.dot(y) 的结果:")
print(x.dot(y))

print("np.dot(x, y) 的结果:")
print(np.dot(x, y))

x.dot(y) 的结果:
[[19. 22.]
 [43. 50.]]
np.dot(x, y) 的结果:
[[19. 22.]
 [43. 50.]]


##### 19.利用13题目中的 x,进行求和。提示：输出三种求和 (1)print(np.sum(x)):   (2)print(np.sum(x，axis =0 ));   (3)print(np.sum(x,axis = 1))

In [55]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 输出三种求和方式
print("所有元素的总和 (np.sum(x)):")
print(np.sum(x))

print("按列求和 (np.sum(x, axis=0)):")
print(np.sum(x, axis=0))

print("按行求和 (np.sum(x, axis=1)):")
print(np.sum(x, axis=1))

所有元素的总和 (np.sum(x)):
10.0
按列求和 (np.sum(x, axis=0)):
[4. 6.]
按行求和 (np.sum(x, axis=1)):
[3. 7.]


#### 20.利用13题目中的 x,进行求平均数（提示：输出三种平均数(1)print(np.mean(x)) (2)print(np.mean(x,axis = 0))(3) print(np.mean(x,axis =1))）

In [56]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 输出三种平均数方式
print("所有元素的平均值 (np.mean(x)):")
print(np.mean(x))

print("按列求平均值 (np.mean(x, axis=0)):")
print(np.mean(x, axis=0))

print("按行求平均值 (np.mean(x, axis=1)):")
print(np.mean(x, axis=1))

所有元素的平均值 (np.mean(x)):
2.5
按列求平均值 (np.mean(x, axis=0)):
[2. 3.]
按行求平均值 (np.mean(x, axis=1)):
[1.5 3.5]


#### 21.利用13题目中的x，对x 进行矩阵转置，然后输出转置后的结果，（提示： x.T 表示对 x 的转置）

In [57]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 对 x 进行矩阵转置，并输出结果
x_transposed = x.T
print("矩阵 x 的转置结果:")
print(x_transposed)

矩阵 x 的转置结果:
[[1. 3.]
 [2. 4.]]


#### 22.利用13题目中的x,求e的指数（提示： 函数 np.exp()）

In [58]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 求 e 的指数（使用 np.exp() 函数）
x_exp = np.exp(x)
print("矩阵 x 的 e 的指数结果:")
print(x_exp)

矩阵 x 的 e 的指数结果:
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


#### 23.利用13题目中的 x,求值最大的下标（提示(1)print(np.argmax(x)) ,(2) print(np.argmax(x, axis =0))(3)print(np.argmax(x),axis =1))

In [59]:
# (1) 使用 13 题目中的 x
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

# (2) 求值最大的下标
# 输出整个矩阵中最大值的索引（扁平化后的索引）
max_index_flat = np.argmax(x)
print(f"整个矩阵中最大值的索引（扁平化）: {max_index_flat}")

# 输出按列求最大值的索引
max_index_axis0 = np.argmax(x, axis=0)
print(f"按列求最大值的索引: {max_index_axis0}")

# 输出按行求最大值的索引
max_index_axis1 = np.argmax(x, axis=1)
print(f"按行求最大值的索引: {max_index_axis1}")

整个矩阵中最大值的索引（扁平化）: 3
按列求最大值的索引: [1 1]
按行求最大值的索引: [1 1]


#### 24,画图，y=x*x 其中 x = np.arange(0, 100, 0.1) （提示这里用到  matplotlib.pyplot 库）

In [60]:
! pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/


In [62]:
# # (1) 导入必要的库
# import numpy as np
# import matplotlib.pyplot as plt

# # (2) 定义 x 和 y
# x = np.arange(0, 100, 0.1)  # x 的范围从 0 到 100，步长为 0.1
# y = x * x  # y = x^2

# # (3) 绘制图形
# plt.figure(figsize=(10, 6))  # 设置画布大小
# plt.plot(x, y, label='y = x^2', color='blue')  # 绘制曲线
# plt.title('y = x^2 图像')  # 设置标题
# plt.xlabel('x')  # 设置 x 轴标签
# plt.ylabel('y')  # 设置 y 轴标签
# plt.legend()  # 显示图例
# plt.grid(True)  # 显示网格
# plt.show()  # 显示图像

import matplotlib.pyplot as plt
x = np.arange(0, 100, 0.1)
plt.plot(x, [i * i for i in x])
plt.legend(['x^2'])


ModuleNotFoundError: No module named 'matplotlib'

#### 25.画图。画正弦函数和余弦函数， x = np.arange(0, 3 * np.pi, 0.1)(提示：这里用到 np.sin() np.cos() 函数和 matplotlib.pyplot 库)

In [ ]:
# (1) 导入必要的库
import numpy as np
import matplotlib.pyplot as plt

# (2) 定义 x 的范围
x = np.arange(0, 3 * np.pi, 0.1)  # x 的范围从 0 到 3π，步长为 0.1

# (3) 计算正弦和余弦函数值
y_sin = np.sin(x)  # 正弦函数
y_cos = np.cos(x)  # 余弦函数

# (4) 绘制图形
plt.figure(figsize=(10, 6))  # 设置画布大小
plt.plot(x, y_sin, label='sin(x)', color='blue')  # 绘制正弦曲线
plt.plot(x, y_cos, label='cos(x)', color='red')  # 绘制余弦曲线

# (5) 添加标题和标签
plt.title('正弦函数和余弦函数图像')  # 设置标题
plt.xlabel('x')  # 设置 x 轴标签
plt.ylabel('y')  # 设置 y 轴标签

# (6) 显示图例和网格
plt.legend()  # 显示图例
plt.grid(True)  # 显示网格

# (7) 显示图像
plt.show()